[package]
name = "rust_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan_fmt = "0.2.6"
slint = "1.12.1"
slint-build = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"
